# Generated by Django 4.2.7 on 2023-12-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active_client',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='max_client',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        # migrations.CreateModel(
        #     name='Message',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('message', models.TextField()),
        #         ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
        #         ('datetime', models.DateTimeField(auto_now_add=True)),
        #         ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
