# Generated by Django 4.2.7 on 2023-12-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_active_client_chatroom_max_client_message'),
        ('chat', '0007_rename_count_chatroom_active_client_and_more'),
    ]

    operations = [
    ]
